service: users-crud
provider:
  name: aws
  runtime: nodejs12.x
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
functions:
  create:
    handler: users/create.create
    events:
      - http:
          path: users/create
          method: post
  list:
    handler: users/list.list
    events:
      - http:
          path: users
          method: get
  get:
    handler: users/get.get
    events:
      - http:
          path: users/{id}
          method: get
  delete:
    handler: users/delete.delete
    events:
      - http:
          path: users/{id}
          method: delete
  update:
    handler: users/update.update
    events:
      - http:
          path: users/{id}
          method: put
resources:
  Resources:
    UsersDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
